name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  - pip:
    - inference-schema[numpy-support]==1.3.0
    - xlrd==2.0.1
    - azureml-core==1.48.0
    - azure-ai-documentintelligence==1.0.0b3
    - azure-ai-ml==1.16.0
    - python-dotenv==0.21.0
